### ISSUE TITLE
Where is railway depoy

### ISSUE THREAD

**Issue by saksham680-lcpro** [subinps/VCPlayerBot#20]
Please tell me

**Comment by staneswilson** [comment]
He may be removed
as many users are being banned

**Comment by Achu2234** [comment]
https://github.com/subinps/VCPlayerBot/issues/7#issue-998439542

**Comment by AmirulAndalib** [comment]
# @Achu2234  due to Jake Cooper showing off  with railway and his poor server he pull requested for removing button so @subinps  removed it :)

**Comment by Achu2234** [comment]
I know it
