### ISSUE TITLE
BUGS IN THE /play COMMAND AND /cplay COMMAND

### ISSUE THREAD

**Issue by ghost** [subinps/VCPlayerBot#48]
I AM THE OWNER OF THE BOT. I CREATED THE BOT USING YOUR [REPO](https://github.com/subinps/VCPlayerBot). I FORWARDED A FILE FROM A CHANNEL AND I SEND IT TO THE BOT. I REPLIED THAT FILE BY PLAY COMMAND. IT REPLIED "🔈 Playlist is empty. Streaming STARTUP_STREAM (https://youtu.be/8NzYo0jmYek) ". SO I THOUGHT THAT IT IS A BUG DUE TO MY NETWORK PROBLEM. BUT AFTER SOME TIME I TRIED IT AGAIN, SAME REPLY. I DO KNOW WHAT TO DO ! THEN I WENT TO MOBILE AND OPENED THE BOT FROM ANOTHER TG ACCOUNT WHICH I AM AN ADMIN IN THE BOT. I TRIED THE SAME . I WAS VERY SHOCKED TO SEE IT IS WORKING. I WONDERED WHY IT IS WORKING IN MOBILE AND NOT IN MY LAPTOP. THEN I TRIED ANOTHER WAY. I OPENED MY ANOTHER ACCOUNT IN TG IN LAP. I TRIED THE SAME , BUT NOT WORKING. [ NOTE :- THE SECOND ACCOUNT IN MY LAP IS NOT AN ADMIN OF THE BOT ] SO, IT IS WORKING ONLY IN MOBILE. I USED THE "fplay" COMMAND TOO. BUT IT IS NOT WORKING

2) C PLAY COMMAND IS NOT WORKING PROPERLY. I GAVE CPLAY COMMAND AND THE CHANNEL ID. IT WAS WORKING. BUT THE FILES ORDER IN THAT CHANNEL WHICH I UPLOADED AND THE STREAMING ORDER IS NOT WORKING PROPERLY.

PLEASE TRY TO FIX THESE ERRORS [ I DO KNOW IT IS A ERROR OR BUG ] OR BUGS ASAP,.
YOURS TRULY,
YOUR FOLLOWER AND FAN.

FIND ME IN TG : [V.SHREERAM](https://t.me/MKSCORPIONLOVER)

**Comment by mk-scorpion** [comment]
> 
> 
> The first issue is a known bug . Some telegram files are not playing since download from tg is unsuccessful. I will be pushing update on that today.
> 
> For cplay, yiu should turn off the shuffle mode using /settings.

MAY I KNOW WHEN YOU WILL FIX IT BRO ?

**Comment by mk-scorpion** [comment]
> 
> 
> > > The first issue is a known bug . Some telegram files are not playing since download from tg is unsuccessful. I will be pushing update on that today.
> > > For cplay, yiu should turn off the shuffle mode using /settings.
> > 
> > 
> > AGAIN THE PROBLEM IN CPLAY BRO. PLEASE HELP ME BRO
> 
> What you mean by problem?

THE ORDER OF THE VIDEOS IN CHANNEL AND THE STREAMING ORDER OF THE VC BOT IS NOT SAME.
