### ISSUE TITLE
No video and audio in stream. Please help

### ISSUE THREAD

**Issue by pavneetsingh-00** [subinps/VCPlayerBot#6]
![Screenshot_2021-09-16-17-48-59-858_org telegram plus](https://user-images.githubusercontent.com/76841477/133610885-09e9bb18-6f1c-4979-8798-ea9010bf9960.jpg)

No video and audio in stream. Please help

**Comment by subinps** [comment]
Use your brain and eyes to read the logs and figure out the issue before raising an issue.
