### ISSUE TITLE
Error deploy

### ISSUE THREAD

**Issue by AlphaEliasPY** [subinps/VCPlayerBot#63]
python3: can't open file '/VCPlayerBot/main.py': [Errno 2] No such file or directory
 :( is error in deploy

**Comment by subinps** [comment]
Where you are deploying?
Heroku?

**Comment by AlphaEliasPY** [comment]
If you are hosted on heroku. I reversed the changes and it worked again for me. I think it is something from the dockerfile because it is what I changed to the previous one

**Comment by subinps** [comment]
Eh?

**Comment by AlphaEliasPY** [comment]
I pushed the changes that were made to the dockerfile of your repository and I did deploy in heroku but it gave me that error and since it gave me that error I put the previous dockerfile back and it worked again, do you think it is a problem with the current dockerfile?

**Comment by AlphaEliasPY** [comment]
I also use the @GetPlayListBot bot to get a playlist and when I put / import it tells me that the playlist is invalid. Check the app.json and everything is fine what is the cause of that error

**Comment by subinps** [comment]
use /yplay

**Comment by AlphaEliasPY** [comment]
Also / ytplay gives an error with a playlist link, it always answers me with this message 
No playList file given. Use @GetPlayListBot  or search for a playlist in @DumpPlaylist to get a playlist file.
