### ISSUE TITLE
Can't schedule live streams using VCPlayer

### ISSUE THREAD

**Issue by ghost** [subinps/VCPlayerBot#66]
Hello @subinps bro ,
I'm right here to tell about a problem in VCPlayer.
I'm trying to schedule a live stream in our channel using [Good Day Channel: By Nava Live](https://t.me/GoodDayChannelNLive_bot)  bot. It's showing “Succesfully scheduled to stream on  Nov 04 2021, 10:00 AM”. But, in my channel, it's not really showing as “Live stream scheduled in Nov 04, 10:00”.
It's not really scheduling. I've tried to cancel the stream, and rescheduled it. I've restarted it.
But, still it didn't scheduled in my channel.
Please fix this issue.

**Comment by subinps** [comment]
It may be an issue with link or file you used.
Scheduling works perfect for me.
If there are any errors, report with recent logs.
