### ISSUE TITLE
Can't schedule live streams using VCPlayer

### ISSUE THREAD

**Issue by Navaneeth-Renjith-8282** [subinps/VCPlayerBot#67]
Hello @subinps ,
I'm right here to tell about a problem in VCPlayer.
I'm trying to schedule a live stream in our channel using [Good Day Channel: By Nava Live](https://t.me/GoodDayChannelNLive_bot)  bot. It's showing “Succesfully scheduled to stream on  Nov 04 2021, 10:00 AM”. But, in my channel, it's not really showing as “Live stream scheduled in Nov 04, 10:00”.
It's not really scheduling. I've tried to cancel the stream, and rescheduled it. I've restarted it.
But, still it didn't scheduled in my channel.
Please fix this issue.

**Comment by subinps** [comment]
Don't raise duplicate issues
https://github.com/subinps/VCPlayerBot/issues/66

**Comment by Navaneeth-Renjith-8282** [comment]
Ok

**Comment by Navaneeth-Renjith-8282** [comment]
#66

**Comment by Navaneeth-Renjith-8282** [comment]
> [31-Oct-21 14:38:37 - INFO] - utils.logger - Title Editing turned off

> [31-Oct-21 14:38:37 - INFO] - utils.logger - Reply Message Found, Enabled PM MSG

> [31-Oct-21 14:38:44 - INFO] - utils.logger - GoodDayChannelNLive_bot Started.

> [31-Oct-21 14:38:45 - WARNING] - utils.logger - No DATABASE_URI , found. It is recommended to use a database.

**Comment by Navaneeth-Renjith-8282** [comment]
Ok. But, this issue is still exists. So, don't close this.

**Comment by Navaneeth-Renjith-8282** [comment]
Hello @subinps ,
Bot logs are showing like this.

> [31-Oct-21 14:38:37 - INFO] - utils.logger - Title Editing turned off

> [31-Oct-21 14:38:37 - INFO] - utils.logger - Reply Message Found, Enabled PM MSG

> [31-Oct-21 14:38:44 - INFO] - utils.logger - GoodDayChannelNLive_bot Started.

> [31-Oct-21 14:38:45 - WARNING] - utils.logger - No DATABASE_URI , found. It is recommended to use a database.
