### ISSUE TITLE
I am getting this error on heroku

### ISSUE THREAD

**Issue by TNO-TheMemer** [subinps/VCPlayerBot#72]
![Screenshot_2021-11-11-19-30-59-130_com android chrome](https://user-images.githubusercontent.com/71560042/141311008-2469c776-4106-497b-87aa-ee74f9407d5b.jpg)

**Comment by TNO-TheMemer** [comment]
Wth 🥲
Isn't there any support group?

**Comment by WeakestHunter43** [comment]
bro use @genStr_Bot bot to generate program session token otherwise it will not work
