### ISSUE TITLE
Please help👇👇👇👇🥺🥺🥺

### ISSUE THREAD

**Issue by phnxXD** [subinps/VCPlayerBot#77]
![Screenshot_2021-12-02-00-08-40-566_com android chrome](https://user-images.githubusercontent.com/76841477/144294040-925af229-c753-4cce-81c5-2ff4002b5d55.jpg)

**Comment by dickenscarl** [comment]
Same issue

**Comment by DarremMolko** [comment]
I'm having this problem too, I get this message:
"Startup was unsuccesfull, Errors - unpack requires a buffer of 267 bytes"

**Comment by HaxNik** [comment]
Same error

**Comment by Code-X-Mania** [comment]
make string session again
