### ISSUE TITLE
Why is it stuck when playing audio in bot?

### ISSUE THREAD

**Issue by Nobita-o** [subinps/VCPlayerBot#8]
when i deploy a bot on heroku and try to play,  Audio does not come clear. audio gets stuck a little bit. deployed 3-4 times but problem is same.
My friend also tried many times.
audio doesn't come clear and smooth.
but why? is it heroku problem or repo?
please fix this asap.

**Comment by subinps** [comment]
https://telegram.org/StopTryingToGetThingsForFree

Get a vps and deploy there.
Or may be an issue with file you play.
